### ISSUE TITLE
'Unexpected token' message when starting the server

### ISSUE THREAD

**Issue by magalhini** [bclinkinbeard/egghead-getting-started-with-express#1]
First of all, thank you so much for putting this course together, I'm loving getting more out of node and express with it!

Halfway through though, I began to have an `SyntaxError: Unexpected token` message when booting up the server, without any more information on where it was. Turns out this isn't a syntax error in the code per se, and it's bound to happen to most Mac users at some point, so I thought I'd share the problem and how to fix it:

That damned `.DS_Store` file in the OSX filesystem.

In the `/` route, we're grabbing all files from that folder, not just the JSON ones. If it encounters something that is not a JSON file, this will of course break since it can't be parsed. `.DS_Store`, being invisible in the file system, will only show up on the logs for the list of all files.

A solution would be to filter all files and narrow them down to only the JSON ones.
Happy expressing!

**Comment by bclinkinbeard** [comment]
Thanks @magalhini, I'm glad you like it!

I'm a little unsure about which code you're referring to, can you point me to it?

**Comment by magalhini** [comment]
Sure!

It's probably not a big deal, but it's always a good reminder of the unexpected things that can happen with our code. In the `app.get('/')` portion of the code, we're checking against all files in the `/users` folder:

`fs.readdir('users', function (err, files) {...}`

And this throws an error (obviously) when it catches a `.DS_Store`file. Sadly, no useful error is thrown, giving us no clue. Only catching `.json` files works of course, but then the following also needs to be updated since the length will no longer be equal to the total files in the folder:

`if (users.length === files.length) res.render('index', {users: users})`

I hope this was clear enough! :)

**Comment by bclinkinbeard** [comment]
Ah ha, thanks @magalhini. I'm not sure why I never encountered that since I am on a Mac as well.

Since that code only exists in a few lessons in the middle, and I haven't seen any other reports of it, I'm going to close this issue without any changes. If it continues to be a problem for people I will update the code in those branches.

Thanks again!

**Comment by magalhini** [comment]
No problem, just thought I'd let a note in case some other students ran into the same issue ;) definitely not something that needs to be addressed. Cheers for listening!
